name: Check Build

on:
  pull_request:
    branches: [staging ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - run: npm ci
      
    - run: npm run lint
      
    - run: npm run build
      env:
        NEXT_PUBLIC_SUPABASE_URL: https://mock.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: mock-key
