name: 🚀 Deploy to Development

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  deploy:
    name: 🔥 Deploy to Firebase App Hosting
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: 📦 Install dependencies
      run: npm ci

    - name: 🔍 Lint code
      run: npm run lint

    - name: 🔐 Create Firebase Service Account Key
      run: |
        echo '${{ env.FIREBASE_SERVICE_ACCOUNT }}' > ${{ runner.temp }}/firebase-service-account.json
      env:
        FIREBASE_SERVICE_ACCOUNT: |
          {
            "type": "service_account",
            "project_id": "daihoiconggiaojp-dev",
            "private_key_id": "5a73ccb9f251c55b9c419002c002e79605113fde",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDHYSb11nGOB8de\nDwCscvIchh8UKGslrp5+G0awzDhlAbKHApCSbp7dlTRISkHFrVjP4uTxMDzqfvWS\nCwsFs5oWAoG0u/YxixQ6WMNZ6RB6VKNV3s3Ai8BXcxAGWGtyZ4IJk1PiJbg9XgP5\nlfQGmCoUXNnvXa5MXy7cHpGOnA84ohwaTLGf6pNggj6n83WvIuQHcTgaD8d79QO0\nE8zwEfo5S+MfVwtZfYleQ+JGkcc7ThaF/Uh+Bgw4zwmtC0ZGdk4dWyDFkFSEnela\nl8qnpGbbYjGel601mkvjoXavDfL81PYL9Dk0QyHekXQTktso//nX1GQiHnKjh4O2\nGZl8mg0XAgMBAAECggEAIj5VarPCHRrI6ya4fuXfH3cJr3Shsn8jSZV1trfcl7yK\n5RVTr1LAhl4x9JiMY186eboGiEY4sC3OD59F7VzDgjQ8Asalqiyw9LR6GN8mrVwM\nEZuKyx81kc95WR2mlqegdfSP26+OzTtwg1V17AwGbijkZXA5l3Rhn/zAEzZKhvdC\n/K7afVB+ORS+SpjaQVEs7FJXwm1FtGLNAZgJy9infG1dPkIMqMsOU1KFTQXOoIYd\nOoOTLROqfwJ8FXHT1p4bVMeAqUU4aypL7sN3b8HFim9kkRqf6qTMawTSfrT5TVQ8\nR4+HmkNtBb6eftwE0MVfFM+tiiqsIZYMV6moMhecQQKBgQDy+PDhp6QWEIUCFiII\nZCLjuCseumwf8CExc0vi72GEGuA29lY+YJxIsEFMWM0GDuWwybggfg3JRW9iGNT0\nCorBR9xI2LI03HgNigUBR8nv/mKPqipF8xXf0pTuerclnDnxzKL5XTT+e5ZPE1pR\nAqAxrb+mYbQ/Y/kTSGEJOPjwfQKBgQDSEdnrtoZFyF705bcdu4wkBz1F15wxD4u9\nDBVYuGaD1M20Q/KK3FIUgN4ul9GW/+ehN8tN1IK7s/FS+Zq6HawwKDeUCpLCTx0l\nTCEcROXOd1wVqXvBBaO9CY+XOc9AUNUFb0PN5nOuXirmd+KTryYboOu/5J4YCo9l\nYcIHLCmcIwKBgFaifQF5DQDxEvwTeD8VtXsNCBME1djtfmhre/uG73ZzPs9aNpY3\nTIJ+lknqv/ARD8Vhp82uJKxHndeUkxoRSDhyrxEqcyB2HDh3piE2v8JbKjmfq0MV\n0g7kv0Xpa7R1aBPXq6TOnz6+QnIfrGyGSyhrk5J39BVGSGGfxTnMnrbhAoGANvFu\nUuVRZy0KEPmIFGG6PK4cC4liE77iKJbhemv4fCCLkMt4w3LukOhHtF4G9nyGI7eJ\nGBkt/FQLGU2pd2ZNY+cQ6kp9qg6xK9Emk9M9W+wCDLRgZtLHyaiXgtEe8M5zeNFq\nJY9R0FhW1iKjA0d7KxzCrFTqOJWCfdy8t82IMIsCgYEAmhs2OO+wmU0IzLnwrT2O\nW9SGZdIOjyJRvHETWheU7ld3b8JZ/FWM6W061ktTNRLpwuctv4+INyrQ+cfjhy86\nwqqHUh2wXy9kNr6xhfMVZ2yCZE3CFy6bORwXZ8wze3VB0rLxZSF8oVTY0UMIJ2Nb\n0/47g044fHBhglHYRPKQwKw=\n-----END PRIVATE KEY-----\n",
            "client_email": "github-actions-dhcg@daihoiconggiaojp-dev.iam.gserviceaccount.com",
            "client_id": "101200661571967036229",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/github-actions-dhcg%40daihoiconggiaojp-dev.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }

    - name: 🔧 Setup Firebase CLI
      run: |
        npm install -g firebase-tools

    - name: 🔐 Authenticate Firebase
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS="${{ runner.temp }}/firebase-service-account.json"
        firebase use daihoiconggiaojp-dev
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-service-account.json

    - name: 🚀 Deploy to Firebase App Hosting
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS="${{ runner.temp }}/firebase-service-account.json"
        firebase deploy --only apphosting
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/firebase-service-account.json
        NEXT_PUBLIC_SUPABASE_URL: https://nlnhhiasteknrfcfnzxd.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sbmhoaWFzdGVrbnJmY2ZuenhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzI3MTgsImV4cCI6MjA2NzY0ODcxOH0.XJwplXGzxW0Wa_nw3WaHYggCiRXqJK5RKgOINvfpxBM
        NEXT_PUBLIC_SITE_URL: https://nlnhhiasteknrfcfnzxd.supabase.co
